/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    404: typeof import('./src/views/404.vue')['default']
    AddressCard: typeof import('./src/components/AddressCard.vue')['default']
    DishCard: typeof import('./src/components/DishCard.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Home: typeof import('./src/views/Home.vue')['default']
    Login: typeof import('./src/views/Login.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    OrderDetail: typeof import('./src/views/OrderDetail.vue')['default']
    OrderList: typeof import('./src/components/OrderList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShoppingCart: typeof import('./src/views/ShoppingCart.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    VanActionBar: typeof import('vant/es')['ActionBar']
    VanActionBarButton: typeof import('vant/es')['ActionBarButton']
    VanActionBarIcon: typeof import('vant/es')['ActionBarIcon']
    VanButton: typeof import('vant/es')['Button']
    VanCard: typeof import('vant/es')['Card']
    VanCol: typeof import('vant/es')['Col']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanRow: typeof import('vant/es')['Row']
    VanSearch: typeof import('vant/es')['Search']
    VanTag: typeof import('vant/es')['Tag']
  }
}
