/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    404: typeof import('./src/views/404.vue')['default']
    AddressCard: typeof import('./src/components/AddressCard.vue')['default']
    DishCard: typeof import('./src/components/DishCard.vue')['default']
    Dishitem: typeof import('./src/components/DishItem.vue')['default']
    DishItem: typeof import('./src/components/DishItem.vue')['default']
    AccpetOrder: typeof import('./src/views/AccpetOrder.vue')['default']
    BottomTabbar: typeof import('./src/components/BottomTabbar.vue')['default']
    Home: typeof import('./src/views/Home.vue')['default']
    Login: typeof import('./src/views/Login.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    OrderCard: typeof import('./src/components/OrderCard.vue')['default']
    MyOrders: typeof import('./src/views/MyOrders.vue')['default']
    OrderDetail: typeof import('./src/views/OrderDetail.vue')['default']
    OrderList: typeof import('./src/components/OrderList.vue')['default']
    Pay: typeof import('./src/components/PayFooter.vue')['default']
    PayFooter: typeof import('./src/components/PayFooter.vue')['default']
    OrderInList: typeof import('./src/components/OrderInList.vue')['default']
    OrderToAccept: typeof import('./src/components/OrderToAccept.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchLine: typeof import('./src/components/SearchLine.vue')['default']
    ShoppingCart: typeof import('./src/views/ShoppingCart.vue')['default']
    SimpleAddressCard: typeof import('./src/components/SimpleAddressCard.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    VanActionBar: typeof import('vant/es')['ActionBar']
    VanActionBarButton: typeof import('vant/es')['ActionBarButton']
    VanActionBarIcon: typeof import('vant/es')['ActionBarIcon']
    Test: typeof import('./src/views/test.vue')['default']
    User: typeof import('./src/views/User.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCard: typeof import('vant/es')['Card']
    VanCol: typeof import('vant/es')['Col']
    VanIcon: typeof import('vant/es')['Icon']
    VanRadio: typeof import('vant/es')['Radio']
    VanRadioGroup: typeof import('vant/es')['RadioGroup']
    VanRow: typeof import('vant/es')['Row']
    VanSearch: typeof import('vant/es')['Search']
    VolunteerCard: typeof import('./src/components/VolunteerCard.vue')['default']
    VanIcon: typeof import('vant/es')['Icon']
    VanList: typeof import('vant/es')['List']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
  }
}
